steps:
  - command: "go build -o dist/my-app ./hello"
    artifact_paths: "./dist/my-app"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
  - block: "Enter Your Name"
  prompt: "Please Enter you First Name"
  fields:
    - text: "Your Name"
    - key: "your-name"
    
