steps:
  - command: "go build -o dist/my-app ./hello"
    artifact_paths: "./dist/my-app"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
  - input: "Enter your First Name"
    fields:
      - text: "What is your First Name?"
        key: "first-name"
    
