steps:
  - command: "go build -o dist/hello ./hello"
    artifact_paths: "./dist/hello"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
  - block: "Name"
    prompt: "Enter your Name"
    fields:
      - text: "First Name"
        key: "first-name"
  - command: "buildkite-agent artifact download test/hello ."

