steps:
  - label: "Build inside container"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
          user: "${BUILDKITE_AGENT_UID}:${BUILDKITE_AGENT_GID}"
    commands: 
        - "go build -o dist/hello ./hello"
        - "chmod -R 777 dist/hello"
    artifact_paths: "./dist/hello"
  - block: "Name"
    prompt: "Enter your Name"
    fields:
      - text: "First Name"
        key: "first-name"
  - command: "buildkite-agent artifact download test/hello ."
    label: "Download the Artifact"
  - command: ".buildkite/run-go.sh"
    label: "Run the Go Application"
